FROM python:2.7-slim

# 替换为 debian buster 归档源
RUN sed -i 's@deb.debian.org@archive.debian.org@g' /etc/apt/sources.list && \
    sed -i 's@security.debian.org@archive.debian.org@g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y gcc build-essential && \
    pip install nrfutil

ENTRYPOINT ["nrfutil"]