FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make \
    gcc-arm-none-eabi \
    binutils-arm-none-eabi \
    openocd \
    gdb-multiarch \
    srecord \
    git \
    python3 \
    python3-pip \
    ca-certificates \
    wget \
    curl \
    libnewlib-arm-none-eabi \
    && rm -rf /var/lib/apt/lists/*

# 安装 nrfutil（python3 版本）
RUN pip3 install --break-system-packages nrfutil

WORKDIR /workspace

CMD ["bash"]